# Generated by Django 5.2.3 on 2025-06-23 07:17

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('pvt_email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('password', models.CharField(blank=True, max_length=8)),
                ('doj', models.DateField(verbose_name='Date of Joining')),
                ('dob', models.DateField(default='2000-01-01', verbose_name='Date of Birth')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='employee_photos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InductionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('q1', models.CharField(max_length=5)),
                ('q2', models.CharField(max_length=5)),
                ('q3', models.CharField(max_length=5)),
                ('q4', models.CharField(max_length=5)),
                ('q5', models.CharField(max_length=5)),
                ('q6', models.CharField(max_length=5)),
                ('q7', models.CharField(max_length=5)),
                ('q8', models.CharField(max_length=5)),
                ('q9', models.CharField(max_length=5)),
                ('q10', models.CharField(max_length=5)),
                ('remark', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='fullname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 23, 7, 17, 56, 531328, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='employee_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('residing_with', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('differently_abled', models.CharField(max_length=10)),
                ('nominee', models.CharField(max_length=10)),
                ('disabled', models.BooleanField(default=False)),
                ('date_of_demise', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QualificationDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification_type', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(max_length=50)),
                ('school_college', models.CharField(max_length=150)),
                ('board_university', models.CharField(max_length=150)),
                ('percentage', models.CharField(max_length=20)),
                ('passing_year', models.CharField(max_length=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='qualifications/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
