# Generated by Django 5.2.3 on 2025-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_employee_inductionfeedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=27314, max_digits=10),
        ),
    ]
