# Generated by Django 5.2.3 on 2025-06-23 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_employeesalary_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_no', models.CharField(max_length=50)),
                ('principal_amount_type', models.CharField(max_length=50)),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_on', models.DateField()),
                ('wef_from', models.DateField(verbose_name='Loan WEF From')),
                ('deduct_from', models.DateField(verbose_name='Loan Deduct From')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.PositiveIntegerField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
