# Generated by Django 5.2.3 on 2025-06-23 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_documentacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRARentProofStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('metro', models.CharField(max_length=10)),
                ('landlord_pan', models.CharField(max_length=50)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_be_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentProofStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('policy_no', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('relation_with_beneficiary', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_be_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
