# Generated by Django 5.2.3 on 2025-06-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_employee_department_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='employee_photos/'),
        ),
    ]
