# Generated by Django 5.2.3 on 2025-06-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('q1', models.CharField(max_length=5)),
                ('q2', models.CharField(max_length=5)),
                ('q3', models.CharField(max_length=5)),
                ('q4', models.CharField(max_length=5)),
                ('q5', models.CharField(max_length=5)),
                ('q6', models.CharField(max_length=5)),
                ('q7', models.CharField(max_length=5)),
                ('q8', models.CharField(max_length=5)),
                ('q9', models.CharField(max_length=5)),
                ('q10', models.CharField(max_length=5)),
                ('remark', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
