# Generated by Django 5.2.3 on 2025-06-23 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
