# Generated by Django 5.2.3 on 2025-06-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_inductionfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InductionFeedback',
        ),
    ]
