# Generated by Django 5.2.3 on 2025-06-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_inductionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('course_type', models.CharField(max_length=50)),
                ('school_college', models.CharField(max_length=150)),
                ('board_university', models.CharField(max_length=150)),
                ('percentage', models.CharField(max_length=20)),
                ('passing_year', models.CharField(max_length=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='qualifications/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
    ]
