# Generated by Django 5.2.3 on 2025-06-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_qualificationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('relation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('residing_with_employee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('differently_abled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('nominee', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('disabled', models.BooleanField(default=False)),
                ('date_of_demise', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
    ]
