# Generated by Django 5.2.3 on 2025-06-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_familymember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
